global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  external_labels:
    monitor: 'meta'

remote_read:
- url: "http://c1-influxdb:8086/api/v1/prom/read?u=user&p=pass&db=c1"
- url: "http://c2-influxdb:8086/api/v1/prom/read?u=user&p=pass&db=c2"
- url: "http://c3-influxdb:8086/api/v1/prom/read?u=user&p=pass&db=c3"

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 5s

  static_configs:
    - targets: ['meta-prom:9090']
